### ISSUE TITLE
How to use Plex-aaos

### ISSUE THREAD

**Issue by nomisa1980** [joeyberkovitz/plex-aaos#11] opened 2022-12-27 20:09 UTC
Hi,

I have multiple users with passcodes and I can't find a user manual for the app. Please can you provide some instructions?

All I'm getting is "Loading Content" with no way to pick a user.

Thanks

Simon

**Comment by joeyberkovitz** [comment] 2022-12-27 20:29
Related to #2

Multi user or PIN protected users can't be supported until the settings screen is added

Loading issues should be improved when the current master branch is released, although the app will still likely be broken in your case.

**Comment by nomisa1980** [comment] 2022-12-27 21:06
Thank you for the reply, I did create a user with no pin, just for the car and music only. The web browser does work for now but it's not a great solution. Is the setting on the current development roadmap?

**Comment by joeyberkovitz** [comment] 2022-12-27 22:32
yes, although at a lower priority to bug fixes, so I can't provide an ETA as to when that will be implemented

**Comment by huibberger** [comment] 2023-02-02 15:29
The AAOS version sees the playlists I made, it shows also the individual songs, but I can’t play a song as I just get  an “player error” or an “media not found error” 
![41A50E9A-B50A-4225-86E3-E39A5EC84253](https://user-images.githubusercontent.com/124280096/216367773-fd9327de-709a-467d-9d5f-41ad47f93d03.jpeg)
![85006B43-692B-49AB-82C5-30ADF03C869B](https://user-images.githubusercontent.com/124280096/216367788-96cdfde0-6ff3-472f-ae68-f346c068c693.jpeg)

**Comment by joeyberkovitz** [comment] 2023-02-02 17:44
@huibberger - let me know roughly what date/time you tried to play the music and I'll try to check the error logs to see if there's something abnormal. Usually once it attempts to play the music, it should be a relatively simple process unless there's something odd with the file formats or playlist setup.

**Comment by huibberger** [comment] 2023-02-02 19:53
﻿
﻿Thank you for getting back to me Joey! I tried again just now (5 - 8 minutes ago).
 I just made up a few simple  playlists for testing. My laptop acts as server, my iPad else were in the  house  plays the playlists o.k. ( that is only the first minute of each track as I do not have taken s subscription yet as I want to be sure it works first before I do….) The car app shows the playlist and the tracks with the details but won’t play- each time I try I get an error message.
Regards and thank you!

Huib Berger

Verstuurd vanaf mijn iPad

Op 2 feb. 2023 om 18:44 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

@huibberger<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhuibberger&data=05%7C01%7C%7C51f53c322b4d4a33d86c08db05452ca5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638109566885020776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GIpj7CbJztc2I%2F0ilD%2B1xVdfBRhTbm9a8dz%2BowcTngE%3D&reserved=0> - let me know roughly what date/time you tried to play the music and I'll try to check the error logs to see if there's something abnormal. Usually once it attempts to play the music, it should be a relatively simple process unless there's something odd with the file formats or playlist setup.

**Comment by joeyberkovitz** [comment] 2023-02-02 20:06
I confirmed that the latest version of the app still works with a fully up to date server. There should be no subscription requirement as I've tested on both servers with and without active Plex pass subscriptions. 

Since the app is showing the album art and full media information, my only guess is that maybe you're using some sort of file format that the media player doesn't support, although since it's not causing an app crash, but instead just a player side error, I don't see any logs.

You can try to make sure your plex server is up to date. Other than that, let me know what type of files are in the playlist (ex: mp3?). Also what operating system is your server running on? I've only tested Linux servers. It shouldn't make a difference but it's possible that something is a bit different between operating systems.

**Comment by huibberger** [comment] 2023-02-02 20:30
Thank you for your reply.

My laptop (=server) runs on Windows 11.
I need to check the format used in the playlist later (when I get home) - I was not aware the file format might be an issue - I think I may have used  FLAC files.
I’ll do another test with mp3

Best regards

Huib Berger

Verstuurd vanaf mijn iPad

Op 2 feb. 2023 om 21:06 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

I confirmed that the latest version of the app still works with a fully up to date server. There should be no subscription requirement as I've tested on both servers with and without active Plex pass subscriptions.

Since the app is showing the album art and full media information, my only guess is that maybe you're using some sort of file format that the media player doesn't support, although since it's not causing an app crash, but instead just a player side error, I don't see any logs.

You can try to make sure your plex server is up to date. Other than that, let me know what type of files are in the playlist (ex: mp3?). Also what operating system is your server running on? I've only tested Linux servers. It shouldn't make a difference but it's possible that something is a bit different between operating systems.

**Comment by joeyberkovitz** [comment] 2023-02-02 21:05
Got it. Google has a note about FLAC potentially requiring an extra plug-in to support ("FLAC"
 https://exoplayer.dev/supported-formats.html#:~:text=constant%20bitrate%20seeking**-,FLAC,-YES). I'll try with FLAC later and see if I get the same errors, and if so will look into adding support for it

**Comment by joeyberkovitz** [comment] 2023-02-02 23:02
tested with both Windows and FLAC with no issues. Only thing I would say is make sure that under the Plex settings, under `Remote Access`, it is both enabled and states `Fully accessible outside your network`. The app will only attempt to connect remotely, so even if the car is on your home WiFi, if remote access isn't configured properly, it won't work.

**Comment by huibberger** [comment] 2023-02-03 15:42
Dear Joey,

For your information: I have checked the settings and access from outside is fully enabled . The playlists I had made before (with FLAC files ) still give errors and won’t play. The new ones I made (mp3 files ) work o.k…….great! So  there may be an issue with FLAC?

Regards

Huib Berger

Verstuurd vanaf mijn iPad

Op 3 feb. 2023 om 00:03 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

tested with both Windows and FLAC with no issues. Only thing I would say is make sure that under the Plex settings, under Remote Access, it is both enabled and states Fully accessible outside your network. The app will only attempt to connect remotely, so even if the car is on your home WiFi, if remote access isn't configured properly, it won't work.

**Comment by joeyberkovitz** [comment] 2023-02-03 15:52
I'm not really sure what the issue is. Based on my testing yesterday, FLAC worked fine, and per the referenced Google doc earlier, FLAC is supported by default since Android 8, and I believe that AAOS only started with Android 10. 

It's possible that maybe the file extension is wrong and it's not really a FLAC file. If you want to debug this issue any further, feel free to email a sample nonfunctional file over to dev@berkovitz.us and I can try to figure out what's going on there. Otherwise it just seems like some sort of file incompatibility or corruption.

**Comment by huibberger** [comment] 2023-02-04 11:35
Thank you again Joey!

The behavior around FLAC files is unfortunately consistent: they don’t play and give an error.
I made new playlists both with mp3 files  and others with other (different) FLAC files. All mp3  files work, none of the FLAC files do!
I copied the same FLAC files on a USB stick and they  play o.k. using AudioWagon, another AAOS car-app (designed to play music from usb sticks), so I’m positive that the files are not corrupted.

What else can I try?

Best regards!

Huib Berger



Verstuurd vanaf mijn iPad

Op 3 feb. 2023 om 16:52 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

I'm not really sure what the issue is. Based on my testing yesterday, FLAC worked fine, and per the referenced Google doc earlier, FLAC is supported by default since Android 8, and I believe that AAOS only started with Android 10.

It's possible that maybe the file extension is wrong and it's not really a FLAC file. If you want to debug this issue any further, feel free to email a sample nonfunctional file over to ***@***.******@***.***> and I can try to figure out what's going on there. Otherwise it just seems like some sort of file incompatibility or corruption.

**Comment by joeyberkovitz** [comment] 2023-02-04 12:29
I managed to replicate the issue. It seems that you're using what Plex calls a Relay to connect to your server.
With the relay, Plex does not allow maximum quality streaming since your data has to path through their servers: https://support.plex.tv/articles/216766168-accessing-a-server-through-relay/#:~:text=Page%3A%20Network-,Limitations,-When%20relaying%20a

My recommendation is to port forward your Plex server through your router as described here: https://support.plex.tv/articles/200931138-troubleshooting-remote-access/. The only alternate option is when I get to #2, I'll figure out what is required to stream music at lower quality, although that defeats the purpose of using FLAC anyway.

**Comment by huibberger** [comment] 2023-02-04 13:49
Thank you Joey, I appreciate your help and will further check into this! I will let you know what I find.

Best regards

Huib


Verstuurd vanaf mijn iPad

Op 4 feb. 2023 om 13:29 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

I managed to replicate the issue. It seems that you're using what Plex calls a Relay to connect to your server.
With the relay, Plex does not allow maximum quality streaming since your data has to path through their servers: https://support.plex.tv/articles/216766168-accessing-a-server-through-relay/#:~:text=Page%3A%20Network-,Limitations,-When%20relaying%20a<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.plex.tv%2Farticles%2F216766168-accessing-a-server-through-relay%2F%23%3A~%3Atext%3DPage%253A%2520Network-%2CLimitations%2C-When%2520relaying%2520a&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105543970294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n0ViLOUZqdQdmgCGLn9N8LLR4Ku84nxwe8jfgt9Xlr4%3D&reserved=0>

My recommendation is to port forward your Plex server through your router as described here: https://support.plex.tv/articles/200931138-troubleshooting-remote-access/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.plex.tv%2Farticles%2F200931138-troubleshooting-remote-access%2F&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105544126068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XiC6jE%2BH%2Fo0AK33ViJ9bUU5oMELyRH7oyp419atwhEk%3D&reserved=0>. The only alternate option is when I get to #2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoeyberkovitz%2Fplex-aaos%2Fissues%2F2&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105544126068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VeFMg0HocN%2B10g8o%2Fnprz%2FBT7tVTmW0pF1YDwe%2BJ5pg%3D&reserved=0>, I'll figure out what is required to stream music at lower quality, although that defeats the purpose of using FLAC anyway.

**Comment by huibberger** [comment] 2023-02-08 12:28
Dear Joey,

Finally success after following your suggestions regarding the relay mode.
I changed the settings earlier this week but noticed that the app was offline at times I tested (picture)

Now it is back and it plays FLAC-files o.k.

Thank you for your support and patience!

Best regards.

Huib Berger

This was the screen I saw  earlier this week.
[image0.jpeg]

Op 4 feb. 2023 om 14:49 heeft Huib Berger ***@***.***> het volgende geschreven:

﻿ Thank you Joey, I appreciate your help and will further check into this! I will let you know what I find.

Best regards

Huib


Verstuurd vanaf mijn iPad

Op 4 feb. 2023 om 13:29 heeft Joey Berkovitz ***@***.***> het volgende geschreven:

﻿

I managed to replicate the issue. It seems that you're using what Plex calls a Relay to connect to your server.
With the relay, Plex does not allow maximum quality streaming since your data has to path through their servers: https://support.plex.tv/articles/216766168-accessing-a-server-through-relay/#:~:text=Page%3A%20Network-,Limitations,-When%20relaying%20a<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.plex.tv%2Farticles%2F216766168-accessing-a-server-through-relay%2F%23%3A~%3Atext%3DPage%253A%2520Network-%2CLimitations%2C-When%2520relaying%2520a&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105543970294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n0ViLOUZqdQdmgCGLn9N8LLR4Ku84nxwe8jfgt9Xlr4%3D&reserved=0>

My recommendation is to port forward your Plex server through your router as described here: https://support.plex.tv/articles/200931138-troubleshooting-remote-access/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.plex.tv%2Farticles%2F200931138-troubleshooting-remote-access%2F&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105544126068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XiC6jE%2BH%2Fo0AK33ViJ9bUU5oMELyRH7oyp419atwhEk%3D&reserved=0>. The only alternate option is when I get to #2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoeyberkovitz%2Fplex-aaos%2Fissues%2F2&data=05%7C01%7C%7C19a543fff8a24d48401908db06ab6c0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111105544126068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VeFMg0HocN%2B10g8o%2Fnprz%2FBT7tVTmW0pF1YDwe%2BJ5pg%3D&reserved=0>, I'll figure out what is required to stream music at lower quality, although that defeats the purpose of using FLAC anyway.

**Comment by joeyberkovitz** [comment] 2023-02-08 12:31
Great, happy to hear that. 

I'm going to close this issue as both the original issue (support for multiple users/servers) and the new issue (streaming high bitrate audio over a relay) will be resolved with #2.

**Closed** 2023-02-08 12:31 UTC
